<html>
<head>
<link type="text/css" rel="stylesheet" href="css/style.css">
</head>
<body>
<div class="obal">
<?php
include_once("inc/hlava.php");

if(isset($_REQUEST["uspech"])){
	echo "<p><strong>You have been sucesfully registered</strong><p>";
	}
	
	if(isset($_REQUEST["neuspech"])){
	echo "<p><strong>Wrong Username or Password</strong><p>";
	}

if(isset($_SESSION["login"])){
	if(!isset($_REQUEST["modralokace"]) && !isset($_REQUEST["zelenalokace"]) && !isset($_REQUEST["cernalokace"]) && !isset($_REQUEST["svetlezelenalokace"]) && !isset($_REQUEST["zlutalokace"]) && !isset($_REQUEST["cervenalokace"]) && !isset($_REQUEST["fialovalokace"])){
	 //<!-- Image Map Generated by http://www.image-map.net/ -->
	echo '<center>';	
	echo '<img src="img/mapa.png" usemap="#image-map">';
echo '<map name="image-map">';
echo '<area target="" alt="" title="" href="index.php?modralokace" coords="369,300,373,280,355,267,342,248,340,240,346,231,345,219,336,214,333,202,328,193,324,184,317,180,317,172,318,163,323,154,332,149,344,150,356,145,370,142,378,140,392,137,402,140,411,143,417,143,424,138,434,131,442,127,455,127,468,127,480,125,492,122,506,125,517,126,523,120,528,118,533,128,536,138,544,150,545,160,543,171,546,179,555,190,559,204,566,216,565,224,565,233,572,242,579,252,582,260,589,264,580,269,562,269,543,264,520,264,502,268,478,278,461,284,442,293,417,297,388,300" shape="poly">';
echo '<area target="" alt="" title="" href="index.php?zelenalokace" coords="528,118,537,110,541,102,537,90,523,88,517,75,524,66,539,65,554,71,565,76,578,79,591,82,604,82,613,86,622,95,637,103,650,110,653,121,659,130,667,141,677,155,686,167,697,192,705,209,708,223,712,240,715,260,712,270,710,278,715,284,719,295,719,304,719,315,714,323,710,330,702,344,700,356,687,378,673,390,657,401,645,405,625,407,611,405,599,413,591,401,578,392,571,378,570,363,581,349,588,330,592,313,594,294,589,272,581,256,567,239,564,217,557,200,553,186,541,176,544,155,537,140" shape="poly">';
echo '<area target="" alt="" title="" href="index.php?cernalokace" coords="713,330,718,340,729,351,738,356,740,366,748,374,757,380,763,383,764,390,770,392,772,404,773,413,776,421,769,432,764,441,762,448,770,457,769,465,763,469,752,476,750,484,749,495,745,504,732,498,722,493,712,496,704,504,690,509,675,509,662,499,650,500,639,503,627,504,627,495,634,489,625,487,611,484,618,474,614,469,602,466,593,460,605,454,614,446,616,433,611,424,608,414,614,407,629,408,647,407,662,400,672,391,682,382,691,372,699,358,703,347,708,337" shape="poly">';
echo '<area target="" alt="" title="" href="index.php?svetlezelenalokace" coords="453,353,458,343,463,333,468,319,468,311,481,313,490,313,498,314,514,310,521,304,525,315,526,322,533,334,535,344,536,353,533,362,526,374,518,377,505,384,488,386,475,386,468,380,468,367,462,358" shape="poly">';
echo '<area target="" alt="" title="" href="index.php?zlutalokace" coords="323,151,323,133,327,124,335,115,342,105,343,93,348,79,339,80,325,83,314,84,306,84,299,79,279,75,269,77,252,74,244,72,224,72,213,79,205,83,199,88,192,97,187,105,180,115,172,128,167,138,162,145,159,160,154,172,150,184,150,199,142,211,139,220,134,230,130,236,123,244,121,260,117,271,127,274,123,284,123,294,131,294,139,292,150,285,161,281,169,279,177,278,189,279,204,280,216,280,228,283,242,284,251,285,252,291,259,293,271,292,289,292,304,294,316,296,325,291,336,292,343,296,355,300,363,302,369,296,371,289,368,279,357,271,350,262,343,253,340,244,345,228,343,217,330,211,326,196,316,182,318,164" shape="poly">';
echo '<area target="" alt="" title="" href="index.php?cervenalokace" coords="158,149,157,161,152,168,150,178,149,190,146,203,140,213,135,225,130,233,125,240,120,253,116,267,126,272,124,282,123,291,125,299,128,310,132,321,137,334,137,345,135,355,129,364,127,372,131,375,139,369,146,373,148,383,150,392,157,400,161,408,162,416,161,425,158,434,152,439,146,441,137,439,126,434,119,432,111,432,103,431,96,431,94,418,87,413,77,405,67,399,56,400,33,399,31,391,31,380,32,372,37,353,37,340,39,332,40,319,42,310,44,299,44,290,46,280,47,271,48,263,46,249,40,231,35,216,35,198,37,182,42,168,49,153,58,142,68,135,85,133,87,124,94,123,101,131,112,140,124,141,136,142,147,142,152,144" shape="poly">';
echo '<area target="" alt="" title="" href="index.php?fialovalokace" coords="93,434,105,430,117,431,129,434,139,441,149,441,156,437,159,427,162,419,160,410,160,402,151,392,149,384,145,375,134,374,126,373,130,362,136,348,138,332,132,318,126,305,124,292,141,289,148,285,161,278,187,276,218,278,245,284,253,289,279,292,291,293,309,295,325,291,336,291,345,296,353,298,375,300,385,300,396,300,407,297,414,298,411,307,409,315,414,322,411,333,405,340,400,350,398,358,399,368,405,378,409,388,413,396,411,402,409,410,414,416,411,428,412,437,407,449,403,456,394,461,386,471,381,475,373,483,362,487,347,495,333,501,315,507,295,511,281,511,271,504,264,509,252,519,240,520,216,524,222,514,211,518,190,521,173,525,152,529,131,532,120,523,126,513,131,507,123,502,115,496,118,488,120,479,120,466,106,457,94,447" shape="poly">';
echo '</map>';
echo '</center>';
	}
	//modralokace
	if(isset($_REQUEST["modralokace"]) && !isset($_REQUEST["zona"])){
		
echo '<center>';
echo '<img src="img/modralokace.png" usemap="#image-map">';

echo '<map name="image-map">';
echo '<area target="" alt="" title="" href="index.php?modralokace&zona=1" coords="345,224,358,221,376,216,396,214,416,209,423,219,434,222,438,229,442,236,454,238,465,242,481,245,489,250,500,255,507,257,514,264,473,277,451,287,431,293,399,297,372,300,372,280,355,272,348,259,342,250,338,236" shape="poly">';
echo '<area target="" alt="" title="" href="index.php?modralokace&zona=2" coords="429,174,411,166,403,162,374,170,355,173,337,176,324,176,313,174,313,181,320,185,323,191,328,202,330,209,337,214,344,224,416,209,415,195,417,184,430,177" shape="poly">';
echo '<area target="" alt="" title="" href="index.php?modralokace&zona=3" coords="403,162,407,155,407,144,394,137,381,139,369,143,360,145,346,148,337,149,328,151,319,158,315,172,327,176,343,176,379,169" shape="poly">';
echo '<area target="" alt="" title="" href="index.php?modralokace&zona=4" coords="402,161,406,154,406,142,416,145,424,137,432,130,448,126,464,126,475,126,484,123,494,122,508,125,518,125,523,119,533,135,543,152,542,169,538,180,516,187,516,187,495,191,486,191,467,191,461,183,450,180,440,178,429,178,415,170,406,167" shape="poly">';
echo '<area target="" alt="" title="" href="index.php?modralokace&zona=5" coords="434,224,442,222,451,220,457,218,461,210,465,203,466,194,465,187,457,181,440,175,431,178,417,184,414,198,416,212,423,220" shape="poly">';
echo '<area target="" alt="" title="" href="index.php?modralokace&zona=6" coords="435,224,439,234,447,238,458,238,466,242,479,245,488,251,502,256,511,258,513,265,523,265,532,265,541,267,549,269,557,269,567,270,573,271,582,270,589,269,582,260,577,251,571,242,566,234,563,225,562,215,560,207,558,198,554,191,548,182,539,179,522,184,508,189,494,191,477,190,470,191,467,197,461,209,458,216,452,219,445,221" shape="poly">';
echo '</map>';
echo '</center>';

	}
	//Modrezony
	if(@$_REQUEST["zona"] == 1){
		echo "<div class='zonemain'>";
			echo "<div class='zonepolicko' style='background-image:url(img/action/fishing.png)'>";
			echo "fishing";
			echo "</div>";
			echo "<div class='zonepolicko' style='background-image:url(img/action/trade.png)'>";
			echo "trading";
			echo "</div>";
			echo "</div>";
			}
			if(@$_REQUEST["zona"] == 2){
			echo "<div class='zonemain'>";
			echo "<div class='zonepolicko' style='background-image:url(img/action/fishing.png)'>";
			echo "fishing";
			echo "</div>";
			echo "<div class='zonepolicko' style='background-image:url(img/action/hunt.png)'>";
			echo "<a href='grouphunt.php'>hunting</a>";
			echo "</div>";
			echo "</div>";
			}
			if(@$_REQUEST["zona"] == 3){
			echo "<div class='zonemain'>";
			echo "<div class='zonepolicko' style='background-image:url(img/action/fishing.png)'>";
			echo "fishing";
			echo "</div>";			
			echo "<div class='zonepolicko' style='background-image:url(img/action/herbalism.png)'>";
			echo "herbalism";
			echo "</div>";
			echo "<div class='zonepolicko' style='background-image:url(img/action/hunt.png)'>";
			echo "<a href='grouphunt.php'>hunting</a>";
			echo "</div>";
			echo "</div>";
			
			}
			if(@$_REQUEST["zona"] == 4){
			echo "<div class='zonemain'>";
			echo "<div class='zonepolicko' style='background-image:url(img/action/fishing.png)'>";
			echo "fishing";
			echo "</div>";
			echo "<div class='zonepolicko' style='background-image:url(img/action/hunt.png)'>";
			echo "<a href='grouphunt.php'>hunting</a>";
			echo "</div>";
			echo "<div class='zonepolicko' style='background-image:url(img/action/mining.png)'>";
			echo "mining";
			echo "</div>";
			echo "</div>";
			}
			if(@$_REQUEST["zona"] == 5){
			//echo "trading<br>working<br>";
			
			echo "<div class='zonemain'>";
			echo "<div class='zonepolicko' style='background-image:url(img/action/trade.png)'>";
			echo "<a href='shop.php?lokace=modralokace&zona=5&trading'>Trade</a>";
			echo "</div>";	
			echo "<div class='zonepolicko' style='background-image:url(img/action/work.png)'>";
			echo "<a href=''>Job</a>";
			echo "</div>";
			echo "</div>";
							
			}
			if(@$_REQUEST["zona"] == 6){
			echo "<div class='zonemain'>";
			echo "<div class='zonepolicko' style='background-image:url(img/action/fishing.png)'>";
			echo "fishing";
			echo "</div>";
			echo "<div class='zonepolicko' style='background-image:url(img/action/hunt.png)'>";
			echo "<a href='grouphunt.php'>hunting</a>";
			echo "</div>";
			echo "<div class='zonepolicko' style='background-image:url(img/action/herbalism.png)'>";
			echo "herbalism";
			echo "</div>";
			echo "<div class='zonepolicko' style='background-image:url(img/action/mining.png)'>";
			echo "mining";
			echo "</div>";
			echo "</div>";
			}
			
		//kdyz kliknes na trade
		if(isset($_REQUEST["trading"])){
			include_once("shop.php");
		}
			
	//tady uz je kdyz nejsi lognutej..
	} else {


?>

<div class="main">
<?php	
if(isset($_REQUEST["spatne"])){
echo "<strong>Zadal jste něco špatně</strong>";
}

if(!isset($_SESSION["login"])){
?>

<form action="loginH.php" method="POST">
<table style="width:50%">
  <tr>
    <th>Login</th>
  </tr>
   <tr>
   <td>Username</td>
   <td>Password</td>
   </tr>
  <tr>
    <td><input type="text" 		name="username" placeholder="username" required></td>
    <td><input type="password" 	name="password" placeholder="password" required></td>
    <td><input type="submit" name="submit" value="Login"></td>
  </tr>
</table>
 </form>

<?php
}
?>

</div>


<?php
}
include_once("inc/pata.php");
?>
</div>
</body>
</html>